config/routes.rb
Rails.application.routes.draw do
  get 'column/sort'
  resources :projects, only: [:show] do
    resources :columns, only: [] do
      member do
        put :sort
      end
      resources :tasks, only: [] do
        member do
          put :sort
        end
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/column.rb
class Column < ApplicationRecord
  include RankedModel
  belongs_to :project
  has_many :tasks

  ranks :row_order
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  has_many :columns
end

app/models/task.rb
class Task < ApplicationRecord
  include RankedModel
  belongs_to :project
  belongs_to :column

  ranks :row_order, with_same: :column_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  def sort
    column = Column.find(params[:id])
    column.update!(row_order_position: params['rowOrderPosition'])
    head :no_content
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find(params[:id])
    @columns = @project.columns.rank(:row_order)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def sort
    task = Task.find(params[:id])
    task.update!(
      row_order_position: params['rowOrderPosition'],
      column_id: params['newColumnId']
    )
    head :no_content
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/column_helper.rb
module ColumnHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Turboboards" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex text-slate-950">
      <%= yield %>
    </main>
  </body>
</html>

app/views/projects/show.html.erb
<div>
  <h1 class="font-bold text-4xl mb-4"><%= @project.title %></h1>

  <div
    class="columns-<%= @columns.size %> gap-4 w-full h-screen flex"
    data-controller="sortable"
  >
    <% @columns.each do |column| %>
      <div
        class="w-full"
        data-sortable-update-url="<%= sort_project_column_path(@project, column) %>"
      >
        <h2 class="font-bold cursor-pointer"><%= column.title %>&colon;</h2>
        <ol
          class="list-none"
          data-controller="sortable"
          data-sortable-group-value="tasks"
          data-sortable-column-id="<%= column.id %>"
        >
          <% column.tasks.rank(:row_order).each do |task| %>
            <li
              class="outline outline-slate-400 rounded-sm p-2 my-2 cursor-pointer"
              data-controller="sortable"
              data-sortable-update-url="<%= sort_project_column_task_path(@project, column, task) %>"
            >
              <%= task.title %>
            </li>
          <% end %>
        </ol>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Task#update</h1>
  <p>Find me in app/views/task/update.html.erb</p>
</div>